### ISSUE TITLE
Any interest in moving to the windows crate?

### ISSUE THREAD

**Issue by hntd187** [Veykril/imgui-dx11-renderer#4]
Hi, I don't know if you are still maintaining this project, but I took the current release and ported it to use the windows crate bindings instead of the raw winapi bindings. 

You can find it [here](https://github.com/hntd187/imgui-dx11-renderer/tree/windows-crate).

Any interest in upstreaming this? I'm currently using it as a local dependency but maybe it can be of use to others.

**Comment by Veykril** [comment]
Sure, I don't see why not 👍

**Comment by hntd187** [comment]
I opened a pr #5
